ship_centre_x: 4      #* Centre of the polygon
ship_centre_y: 0
ship_centre_z: 2

radius: 4.5           #* Radius of the polygon

n_sides: 8            #* No. of sides of the polygon

transition_rate: 0.75 #* Wait time between side transition
